# DNS Leak / IP Leak Test
DOMAIN-SUFFIX,dnsleaktest.com
DOMAIN-SUFFIX,browserleaks.com
DOMAIN-SUFFIX,ipleak.net
DOMAIN-SUFFIX,whoer.net
DOMAIN-SUFFIX,dnscheck.tools
DOMAIN-SUFFIX,doileak.com
DOMAIN-SUFFIX,test-ipv6.com

# keyword match
DOMAIN-KEYWORD,dnsleak
DOMAIN-KEYWORD,dns-leak
DOMAIN-KEYWORD,ipleak
DOMAIN-KEYWORD,ip-leak
DOMAIN-KEYWORD,browserleaks
DOMAIN-KEYWORD,whoer
DOMAIN-KEYWORD,myip
DOMAIN-KEYWORD,whatismyip
DOMAIN-KEYWORD,iplocation

# public DNS IP
IP-CIDR,104.245.13.13/24,no-resolve
IP-CIDR,216.23.95.68/24,no-resolve
IP-CIDR,8.8.8.0/24,no-resolve
IP-CIDR,9.9.9.9/32,no-resolve
IP-CIDR,8.8.8.8/32,no-resolve
IP-CIDR,8.8.4.4/32,no-resolve
IP-CIDR,1.1.1.1/32,no-resolve
IP-CIDR,1.0.0.1/32,no-resolve
