CREATE TABLE IF NOT EXISTS `homepage_settings` (
  `id` int(11) NOT NULL,
  `hero_eyebrow` varchar(120) NOT NULL DEFAULT 'Software Engineering Notes',
  `hero_title` varchar(160) NOT NULL DEFAULT 'Mooncci Blog',
  `hero_subtitle` varchar(500) NOT NULL DEFAULT '记录 Web 开发、Linux、OpenWrt、网络技术、系统设计和项目实践中的经验与踩坑。',
  `hero_description` text,
  `primary_cta_label` varchar(80) NOT NULL DEFAULT '开始阅读',
  `primary_cta_url` varchar(255) NOT NULL DEFAULT '/articles',
  `secondary_cta_label` varchar(80) NOT NULL DEFAULT '查看最新文章',
  `secondary_cta_url` varchar(255) NOT NULL DEFAULT '#latest',
  `hero_chips_json` text,
  `featured_badge` varchar(80) NOT NULL DEFAULT '推荐阅读',
  `featured_fallback_title` varchar(200) NOT NULL DEFAULT '精选文章正在准备中',
  `featured_fallback_summary` text,
  `latest_eyebrow` varchar(80) NOT NULL DEFAULT 'Latest Posts',
  `latest_title` varchar(120) NOT NULL DEFAULT '最近更新',
  `latest_description` varchar(500) DEFAULT NULL,
  `topics_eyebrow` varchar(80) NOT NULL DEFAULT 'Topics',
  `topics_title` varchar(120) NOT NULL DEFAULT '技术专栏',
  `topics_json` text,
  `about_eyebrow` varchar(80) NOT NULL DEFAULT 'About',
  `about_title` varchar(120) NOT NULL DEFAULT '关于作者',
  `about_intro` varchar(500) DEFAULT NULL,
  `about_description` text,
  `about_email` varchar(160) DEFAULT NULL,
  `about_github` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `homepage_settings`
(
  `id`,
  `hero_eyebrow`,
  `hero_title`,
  `hero_subtitle`,
  `hero_description`,
  `primary_cta_label`,
  `primary_cta_url`,
  `secondary_cta_label`,
  `secondary_cta_url`,
  `hero_chips_json`,
  `featured_badge`,
  `featured_fallback_title`,
  `featured_fallback_summary`,
  `latest_eyebrow`,
  `latest_title`,
  `latest_description`,
  `topics_eyebrow`,
  `topics_title`,
  `topics_json`,
  `about_eyebrow`,
  `about_title`,
  `about_intro`,
  `about_description`,
  `about_email`,
  `about_github`
)
VALUES
(
  1,
  'Software Engineering Notes',
  'Mooncci Blog',
  '记录 Web 开发、Linux、OpenWrt、网络技术、系统设计和项目实践中的经验与踩坑。',
  '这里是一份长期积累的工程笔记：从前端界面、后端接口、数据库、部署排障，到路由器和网络监控，把真正踩过的坑写清楚。',
  '开始阅读',
  '/articles',
  '查看最新文章',
  '#latest',
  '["持续更新中","Web / Linux / OpenWrt / 网络","项目实践"]',
  '推荐阅读',
  '精选文章正在准备中',
  '当有文章发布后，这里会展示最值得先读的一篇内容，让读者第一眼看到真正有价值的技术记录。',
  'Latest Posts',
  '最近更新',
  '最新文章放在最前面，方便快速判断这个博客最近在持续写什么。',
  'Topics',
  '技术专栏',
  '[{"title":"Web 全栈开发","description":"React、Node.js、接口设计、前后端协作和真实项目里的工程细节。","icon":"code","to":"/category/Web 全栈开发"},{"title":"Linux / OpenWrt","description":"服务器部署、路由器折腾、服务监控，以及系统层面的排障记录。","icon":"terminal","to":"/category/Linux"},{"title":"网络技术","description":"Nginx、Cloudflare、反向代理、连接跟踪和家庭网络实践。","icon":"network","to":"/category/网络技术"},{"title":"数据库 / 软件工程","description":"MySQL 表结构、迁移、权限边界、测试和长期维护的方法。","icon":"database","to":"/category/数据库"},{"title":"项目实践","description":"把一个个人站从能跑，整理到安全、可部署、可持续维护。","icon":"server","to":"/articles"}]',
  'About',
  '关于作者',
  '我是 Mooncci，一名软件工程学生，也是在持续补齐工程能力的全栈开发学习者。',
  '目前主要关注 Web 开发、网络、系统部署、数据库设计和项目实践。这个博客会尽量把“为什么这么做”“哪里容易坏”“怎么验证”写清楚。',
  'websiteaccount@mooncci.site',
  'https://github.com/'
);

CREATE TABLE IF NOT EXISTS `announcements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(160) NOT NULL,
  `content` text NOT NULL,
  `link_label` varchar(80) DEFAULT NULL,
  `link_url` varchar(255) DEFAULT NULL,
  `status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
  `pinned` tinyint(1) NOT NULL DEFAULT '0',
  `published_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_announcements_status_pinned` (`status`, `pinned`),
  KEY `idx_announcements_published_at` (`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
