CREATE TABLE IF NOT EXISTS `router_monitor_metrics` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `device` varchar(100) NOT NULL DEFAULT 'main-router',
  `conntrack_count` int(10) unsigned DEFAULT NULL,
  `conntrack_max` int(10) unsigned DEFAULT NULL,
  `conntrack_usage` decimal(6,2) DEFAULT NULL,
  `cpu_usage` decimal(6,2) DEFAULT NULL,
  `load_one` decimal(8,2) DEFAULT NULL,
  `load_five` decimal(8,2) DEFAULT NULL,
  `load_fifteen` decimal(8,2) DEFAULT NULL,
  `memory_total_mb` int(10) unsigned DEFAULT NULL,
  `memory_used_mb` int(10) unsigned DEFAULT NULL,
  `memory_free_mb` int(10) unsigned DEFAULT NULL,
  `memory_usage` decimal(6,2) DEFAULT NULL,
  `disk_total_mb` int(10) unsigned DEFAULT NULL,
  `disk_used_mb` int(10) unsigned DEFAULT NULL,
  `disk_free_mb` int(10) unsigned DEFAULT NULL,
  `disk_usage` decimal(6,2) DEFAULT NULL,
  `uptime_seconds` bigint(20) unsigned DEFAULT NULL,
  `overall_usage` decimal(6,2) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_router_monitor_device_created_at` (`device`, `created_at`),
  KEY `idx_router_monitor_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
